# Generated by Django 5.1.3 on 2025-12-22 00:10
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hud", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="image_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="item",
            name="image_url",
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
