# Generated by Django 5.1.3 on 2025-12-22 00:30
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hud", "0002_add_images"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="character",
            name="image_url",
        ),
        migrations.RemoveField(
            model_name="item",
            name="image_url",
        ),
        migrations.AddField(
            model_name="character",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="characters/"),
        ),
        migrations.AddField(
            model_name="item",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="items/"),
        ),
    ]
