# Generated by Django 5.1.3 on 2025-12-22 00:45
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hud", "0003_image_uploads"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="inventory_capacity",
            field=models.PositiveIntegerField(default=16),
        ),
    ]
