# Generated by Django 5.1.3 on 2025-12-22 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hud", "0005_campaign_character_campaign_item_campaign"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="display_name",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="nickname",
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
