# Generated by Django 5.1.3 on 2025-12-23 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hud", "0007_passwordresettoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="visible",
            field=models.BooleanField(default=True),
        ),
    ]
