# Generated by Django 5.1.3 on 2025-12-23 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hud", "0008_character_visible"),
    ]

    operations = [
        migrations.CreateModel(
            name="CharacterBar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("current", models.IntegerField(default=0)),
                ("max_value", models.IntegerField(default=100)),
                ("color", models.CharField(default="#ff4444", max_length=20)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bars",
                        to="hud.character",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
    ]
