# Generated by Django 5.1.3 on 2026-08-05 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hud', '0010_migrate_hp_sp_to_bars'),
        ('hud', '0011_characterattribute_npcattribute'),
    ]

    operations = [
    ]
