# Generated by Django 5.2.17 on 2026-09-08 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hud', '0027_texto_do_post_it_sem_limite_curto'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='image_ferido',
            field=models.ImageField(blank=True, null=True, upload_to='characters/'),
        ),
        migrations.AddField(
            model_name='character',
            name='image_grave',
            field=models.ImageField(blank=True, null=True, upload_to='characters/'),
        ),
    ]
